const booksData = [
  {
    id: 10001,
    title: "Pride and Prejudice ( गर्व आणि पूर्वग्रह )",
    author: "Jane Austen/ ( जेन ऑस्टिन )",
    category: "NOVEL ( कादंबरी )",
  },
  {
    id: 10002,
    title: "Moby Dick ( मोबि डिक )",
    author: "Herman Melville/ ( हर्मन मेलव्हिल )",
    category: "NOVEL ( कादंबरी )",
  },
  {
    id: 10003,
    title: "War and Peace ( वॉर अँड पीस )",
    author: "Leo Tolstoy/ ( लिओ टॉलस्टॉय )",
    category: "NOVEL ( कादंबरी )",
  },
  {
    id: 10004,
    title: "Great Expectations ( ग्रेट एक्स्पेक्टेशन्स )",
    author: "Charles Dickens/ ( चार्ल्स डिकन्स )",
    category: "NOVEL ( कादंबरी )",
  },
  {
    id: 10005,
    title: "Ulysses ( युलिसिस )",
    author: "James Joyce/ ( जेम्स जॉइस )",
    category: "NOVEL ( कादंबरी )",
  },
  {
    id: 10006,
    title: "The Great Gatsby ( द ग्रेट गॅट्सबी )",
    author: "F. Scott Fitzgerald/ ( एफ. स्कॉट फिट्झगेराल्ड )",
    category: "NOVEL ( कादंबरी )",
  },
  {
    id: 10007,
    title: "Anna Karenina ( अ‍ॅना कॅरेनिना )",
    author: "Leo Tolstoy/ ( लिओ टॉलस्टॉय )",
    category: "NOVEL ( कादंबरी )",
  },
  {
    id: 10008,
    title: "To Kill a Mockingbird ( टू किल अ मॉकिंगबर्ड )",
    author: "Harper Lee/ ( हार्पर ली )",
    category: "NOVEL ( कादंबरी )",
  },
  {
    id: 10009,
    title: "Don Quixote ( डॉन क्विक्सोटे )",
    author: "Miguel de Cervantes/ ( मिगेल डे सर्व्ह्हांतेस )",
    category: "NOVEL ( कादंबरी )",
  },
  {
    id: 10010,
    title: "The Brothers Karamazov ( द ब्रदर्स करामाझोव्ह )",
    author: "Fyodor Dostoevsky/ ( फ्योदर दोस्तोयेव्स्की )",
    category: "NOVEL ( कादंबरी )",
  },
  {
    id: 20001,
    title: "Hamlet ( हॅम्लेट )",
    author: "William Shakespeare/ ( विल्यम शेक्सपियर )",
    category: "DRAMA ( नाटक )",
  },
  {
    id: 20002,
    title: "Othello ( ओथेलो )",
    author: "William Shakespeare/ ( विल्यम शेक्सपियर )",
    category: "DRAMA ( नाटक )",
  },
  {
    id: 20003,
    title: "Macbeth ( मॅकबेथ )",
    author: "William Shakespeare/ ( विल्यम शेक्सपियर )",
    category: "DRAMA ( नाटक )",
  },
  {
    id: 20004,
    title: "King Lear ( किंग लिअर )",
    author: "William Shakespeare/ ( विल्यम शेक्सपियर )",
    category: "DRAMA ( नाटक )",
  },
  {
    id: 20005,
    title: "The Tempest ( द टेम्पेस्ट )",
    author: "William Shakespeare/ ( विल्यम शेक्सपियर )",
    category: "DRAMA ( नाटक )",
  },
  {
    id: 20006,
    title: "A Doll's House ( अ डॉल्स हाऊस )",
    author: "Henrik Ibsen/ ( हेन्रिक इब्सेन )",
    category: "DRAMA ( नाटक )",
  },
  {
    id: 20007,
    title: "Pygmalion ( पिग्मॅलियन )",
    author: "George Bernard Shaw/ ( जॉर्ज बर्नार्ड शॉ )",
    category: "DRAMA ( नाटक )",
  },
  {
    id: 20008,
    title: "Waiting for Godot ( वेटिंग फॉर गोडो )",
    author: "Samuel Beckett/ ( सॅम्युएल बेक्केट )",
    category: "DRAMA ( नाटक )",
  },
  {
    id: 20009,
    title: "Death of a Salesman ( डेथ ऑफ अ सेल्समन )",
    author: "Arthur Miller/ ( आर्थर मिलर )",
    category: "DRAMA ( नाटक )",
  },
  {
    id: 20010,
    title: "The Cherry Orchard ( द चेरी ऑर्चर्ड )",
    author: "Anton Chekhov/ ( अँटोन चेखव )",
    category: "DRAMA ( नाटक )",
  },
  {
    id: 30001,
    title: "National Geographic ( नॅशनल जिओग्राफिक )",
    author: "Various/ ( विविध )",
    category: "MAGAZINE ( मासिक )",
  },
  {
    id: 30002,
    title: "TIME ( टाइम )",
    author: "Various/ ( विविध )",
    category: "MAGAZINE ( मासिक )",
  },
  {
    id: 30003,
    title: "Forbes ( फोर्ब्स )",
    author: "Various/ ( विविध )",
    category: "MAGAZINE ( मासिक )",
  },
  {
    id: 30004,
    title: "The Economist ( द इकॉनॉमिस्ट )",
    author: "Various/ ( विविध )",
    category: "MAGAZINE ( मासिक )",
  },
  {
    id: 30005,
    title: "Reader's Digest ( रीडर्स डायजेस्ट )",
    author: "Various/ ( विविध )",
    category: "MAGAZINE ( मासिक )",
  },
  {
    id: 30006,
    title: "Scientific American ( सायंटिफिक अमेरिकन )",
    author: "Various/ ( विविध )",
    category: "MAGAZINE ( मासिक )",
  },
  {
    id: 30007,
    title: "The New Yorker ( द न्यू यॉर्कर )",
    author: "Various/ ( विविध )",
    category: "MAGAZINE ( मासिक )",
  },
  {
    id: 30008,
    title: "Harvard Business Review ( हार्वर्ड बिझनेस रिव्ह्यू )",
    author: "Various/ ( विविध )",
    category: "MAGAZINE ( मासिक )",
  },
  {
    id: 30009,
    title: "Vogue ( व्होग )",
    author: "Various/ ( विविध )",
    category: "MAGAZINE ( मासिक )",
  },
  {
    id: 30010,
    title: "Nature ( नेचर )",
    author: "Various/ ( विविध )",
    category: "MAGAZINE ( मासिक )",
  },
  {
    id: 40001,
    title: "The Diary of a Young Girl ( द डायरी ऑफ अ यंग गर्ल )",
    author: "Anne Frank/ ( ॲन फ्रँक )",
    category: "HISTORICAL ( ऐतिहासिक )",
  },
  {
    id: 40002,
    title: "Team of Rivals ( टीम ऑफ राइव्हल्स )",
    author: "Doris Kearns Goodwin/ ( डोरिस किअर्न्स गुडविन )",
    category: "HISTORICAL ( ऐतिहासिक )",
  },
  {
    id: 40003,
    title: "1776 ( १७७६ )",
    author: "David McCullough/ ( डेविड मॅककुलो )",
    category: "HISTORICAL ( ऐतिहासिक )",
  },
  {
    id: 40004,
    title: "Guns, Germs, and Steel ( गन्स, जर्म्स अँड स्टील )",
    author: "Jared Diamond/ ( जॅरेड डायमंड )",
    category: "HISTORICAL ( ऐतिहासिक )",
  },
  {
    id: 40005,
    title: "The Wright Brothers ( द राईट ब्रदर्स )",
    author: "David McCullough/ ( डेविड मॅककुलो )",
    category: "HISTORICAL ( ऐतिहासिक )",
  },
  {
    id: 40006,
    title:
      "The Rise and Fall of the Third Reich ( द राईज अँड फॉल ऑफ द थर्ड राईक )",
    author: "William Shirer/ ( विल्यम शायरर )",
    category: "HISTORICAL ( ऐतिहासिक )",
  },
  {
    id: 40007,
    title: "Catherine the Great ( कॅथरीन द ग्रेट )",
    author: "Robert K. Massie/ ( रॉबर्ट के. मॅसी )",
    category: "HISTORICAL ( ऐतिहासिक )",
  },
  {
    id: 40008,
    title: "The Liberation Trilogy ( द लिबरेशन ट्रिलॉजी )",
    author: "Rick Atkinson/ ( रिक अ‍ॅटकिन्सन )",
    category: "HISTORICAL ( ऐतिहासिक )",
  },
  {
    id: 40009,
    title: "The History of the Ancient World ( द हिस्टरी ऑफ द अँशंट वर्ल्ड )",
    author: "Susan Wise Bauer/ ( सुसान वाईज बाउर )",
    category: "HISTORICAL ( ऐतिहासिक )",
  },
  {
    id: 40010,
    title:
      "SPQR: A History of Ancient Rome ( एसपीक्यूआर: अ हिस्टरी ऑफ अँशंट रोम )",
    author: "Mary Beard/ ( मेरी बेअर्ड )",
    category: "HISTORICAL ( ऐतिहासिक )",
  },
  {
    id: 50001,
    title: "Essays of Michel de Montaigne ( निबंध - मिशेल डे माँतेन )",
    author: "Michel de Montaigne/ ( मिशेल डे माँतेन )",
    category: "LITERATURE ( साहित्य )",
  },
  {
    id: 50002,
    title: "Divine Comedy ( डिवाइन कॉमेडी )",
    author: "Dante Alighieri/ ( दांते आलिघियेरी )",
    category: "LITERATURE ( साहित्य )",
  },
  {
    id: 50003,
    title: "The Iliad ( द इलियड )",
    author: "Homer/ ( होमर )",
    category: "LITERATURE ( साहित्य )",
  },
  {
    id: 50004,
    title: "The Odyssey ( द ओडिसी )",
    author: "Homer/ ( होमर )",
    category: "LITERATURE ( साहित्य )",
  },
  {
    id: 50005,
    title: "Les Misérables ( लेस मिजरब्ल्स )",
    author: "Victor Hugo/ ( व्हिक्टर ह्यूगो )",
    category: "LITERATURE ( साहित्य )",
  },
  {
    id: 50006,
    title: "Faust ( फॉस्ट )",
    author: "Johann Wolfgang von Goethe/ ( योहान वुल्फगँग वॉन गोएथे )",
    category: "LITERATURE ( साहित्य )",
  },
  {
    id: 50007,
    title: "The Divine Songs ( द डिवाइन साँग्स )",
    author: "Isaac Watts/ ( आयझॅक वॉट्स )",
    category: "LITERATURE ( साहित्य )",
  },
  {
    id: 50008,
    title: "Beowulf ( बियोवुल्फ )",
    author: "Anonymous/ ( अज्ञात )",
    category: "LITERATURE ( साहित्य )",
  },
  {
    id: 50009,
    title: "Paradise Loot ( पॅराडाईज लॉस्ट )",
    author: "John Milton/ ( जॉन मिल्टन )",
    category: "LITERATURE ( साहित्य )",
  },
  {
    id: 50010,
    title: "Canterbury Tales ( कॅंटरबरी टेल्स )",
    author: "Geoffrey Chaucer/ ( जॉफ्री चॉसर )",
    category: "LITERATURE ( साहित्य )",
  },
  {
    id: 60001,
    title: "The Prince ( द प्रिन्स )",
    author: "Niccolò Machiavelli/ ( निकोलो मॅकियावेली )",
    category: "POLITICAL ( राजकीय )",
  },
  {
    id: 60002,
    title: "The Republic ( द रिपब्लिक )",
    author: "Plato/ ( प्लेटो )",
    category: "POLITICAL ( राजकीय )",
  },
  {
    id: 60003,
    title: "Democracy in America ( डेमॉक्रसी इन अमेरिका )",
    author: "Alexis de Tocqueville/ ( अलेक्सिस डे टोकेव्हिल )",
    category: "POLITICAL ( राजकीय )",
  },
  {
    id: 60004,
    title: "The Communist Manifesto ( द कम्युनिस्ट मॅनिफेस्टो )",
    author:
      "Karl Marx & Friedrich Engels/ ( कार्ल मार्क्स आणि फ्रेडरिक एंगेल्स )",
    category: "POLITICAL ( राजकीय )",
  },
  {
    id: 60005,
    title: "Politics ( पॉलिटिक्स )",
    author: "Aristotle/ ( अरिस्टॉटल )",
    category: "POLITICAL ( राजकीय )",
  },
  {
    id: 70001,
    title: "The Raven ( द रेव्हन )",
    author: "Edgar Allan Poe/ ( एडगर ॲलन पो )",
    category: "POEM ( कविता )",
  },
  {
    id: 70002,
    title: "Paradise Lost ( पॅराडाईज लॉस्ट )",
    author: "John Milton/ ( जॉन मिल्टन )",
    category: "POEM ( कविता )",
  },
  {
    id: 70003,
    title: "Leaves of Grass ( लीव्ह्ज ऑफ ग्रास )",
    author: "Walt Whitman/ ( वॉल्ट व्हिटमन )",
    category: "POEM ( कविता )",
  },
  {
    id: 70004,
    title: "Divine Comedy ( डिवाईन कॉमेडी )",
    author: "Dante Alighieri/ ( दांते आलिघियेरी )",
    category: "POEM ( कविता )",
  },
  {
    id: 70005,
    title:
      "Songs of Innocence and Experience ( सॉन्ग्स ऑफ इनोसन्स अँड एक्स्पिरिअन्स )",
    author: "William Blake/ ( विल्यम ब्लेक )",
    category: "POEM ( कविता )",
  },
  {
    id: 80001,
    title: "The Alchemist ( द अल्केमिस्ट )",
    author: "Paulo Coelho/ ( पाउलो कोएलो )",
    category: "FICTION ( काल्पनिक )",
  },
  {
    id: 80002,
    title: "Life of Pi ( लाईफ ऑफ पाय )",
    author: "Yann Martel/ ( यान मार्टेल )",
    category: "FICTION ( काल्पनिक )",
  },
  {
    id: 80003,
    title: "The Kite Runner ( द काईट रनर )",
    author: "Khaled Hosseini/ ( खालिद होसेनी )",
    category: "FICTION ( काल्पनिक )",
  },
  {
    id: 80004,
    title: "The Old Man and the Sea ( द ओल्ड मॅन अँड द सी )",
    author: "Ernest Hemingway/ ( अर्नेस्ट हेमिंग्वे )",
    category: "FICTION ( काल्पनिक )",
  },
  {
    id: 80005,
    title: "The Road ( द रोड )",
    author: "Cormac McCarthy/ ( कॉर्मॅक मॅककार्थी )",
    category: "FICTION ( काल्पनिक )",
  },
  {
    id: 90001,
    title:
      "Sapiens: A Brief History of Humankind ( सेपियन्स: अ ब्रीफ हिस्ट्री ऑफ ह्युमनकाइंड )",
    author: "Yuval Noah Harari/ ( युवाल नोआ हरारी )",
    category: "NON_FICTION ( अकाल्पनिक )",
  },
  {
    id: 90002,
    title: "Educated ( एज्युकेटेड )",
    author: "Tara Westover/ ( तारा वेस्टओव्हर )",
    category: "NON_FICTION ( अकाल्पनिक )",
  },
  {
    id: 90003,
    title:
      "The Immortal Life of Henrietta Lacks ( द इमॉर्टल लाईफ ऑफ हेन्रीएटा लॅक्स )",
    author: "Rebecca Skloot/ ( रेबेका स्क्लूट )",
    category: "NON_FICTION ( अकाल्पनिक )",
  },
  {
    id: 90004,
    title: "Thinking, Fast and Slow ( थिंकिंग, फास्ट अँड स्लो )",
    author: "Daniel Kahneman/ ( डॅनियल कानमॅन )",
    category: "NON_FICTION ( अकाल्पनिक )",
  },
  {
    id: 90005,
    title: "Into the Wild ( इंटु द वाइल्ड )",
    author: "Jon Krakauer/ ( जॉन क्राकॉवर )",
    category: "NON_FICTION ( अकाल्पनिक )",
  },
  {
    id: 100076,
    title: "Indian Home Cooking ( इंडियन होम कुकिंग )",
    author: "Suvir Saran ( सुवीर सरन )",
    category: "RECIPE ( रेसिपी )",
  },
  {
    id: 100077,
    title:
      "The Complete Vegetarian Cookbook ( द कम्प्लीट व्हेजिटेरियन कुकबुक )",
    author: "America's Test Kitchen ( अमेरिका'स टेस्ट किचन )",
    category: "RECIPE ( रेसिपी )",
  },
  {
    id: 100078,
    title: "Flavors of India ( फ्लेवर्स ऑफ इंडिया )",
    author: "Madhur Jaffrey ( माधुर जाफ्रे )",
    category: "RECIPE ( रेसिपी )",
  },
  {
    id: 100079,
    title: "Tiffin: 500 Authentic Recipes ( टिफिन: ५०० ऑथेन्टिक रेसिपीज )",
    author: "Pankaj Bhadouria ( पंकज भदौरिया )",
    category: "RECIPE ( रेसिपी )",
  },
  {
    id: 100080,
    title: "The Curry Secret ( द करी सीक्रेट )",
    author: "Kris Dhillon ( क्रिस धिल्लोन )",
    category: "RECIPE ( रेसिपी )",
  },
];

export default booksData;
